// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['firebaseapikeyone']!,
    appId: '1:743846062080:web:11f624dcaaf028bb9990e5',
    messagingSenderId: '743846062080',
    projectId: 'eduvista-app',
    authDomain: 'eduvista-app.firebaseapp.com',
    storageBucket: 'eduvista-app.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['firebaseapikeytwo']!,
    appId: '1:743846062080:android:a8d5cfc5fbe905f69990e5',
    messagingSenderId: '743846062080',
    projectId: 'eduvista-app',
    storageBucket: 'eduvista-app.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['firebaseapikeythree']!,
    appId: '1:743846062080:ios:2349a883284c73849990e5',
    messagingSenderId: '743846062080',
    projectId: 'eduvista-app',
    storageBucket: 'eduvista-app.appspot.com',
    iosClientId:
        '743846062080-asl40uk89iduip9cm206snulkmqrstro.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduvista',
  );
}
